SANDBOX_URL = "https://apisandbox.dev.clover.com"
RECEIPT_URL_PREFIX = "https://sandbox.dev.clover.com/r/"
API_KEY = "something"
MERCHANT_ID = "someone"
STRIPE_SECRET_KEY = "stripe"
GMAIL_PASSWORD = "hunter2"
GMAIL_USER = "you@gmail.com"
